[package]
name = "mongo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.mongodb]
version = "2.1.0"
default-features = false
features = ["sync"]

[dependencies]
actix-web = "4.0.1"
serde = "1.0.136"
